
CREATE TABLE MKT_PLACE.USUARIO(
	ID_USUARIO NUMBER NOT NULL,
	LOGIN VARCHAR2(255) NOT NULL,
	SENHA VARCHAR2(255) NOT NULL,
	PRIMARY KEY(ID_USUARIO)	
);

CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE CARGO(
	ID_CARGO NUMBER NOT NULL,
	NOME VARCHAR2(255) NOT NULL,
	PRIMARY KEY (ID_CARGO)
)

CREATE SEQUENCE SEQ_CARGO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE USUARIO_CARGO(
	ID_USUARIO NUMBER NOT NULL,
	ID_CARGO NUMBER NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_CARGO),
	CONSTRAINT FK_USUARIO_CARGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_USUARIO_CARGO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
)

SELECT ID_USUARIO, COUNT(*)
FROM USUARIO
GROUP BY ID_USUARIO
HAVING COUNT(*) > 1;

CREATE TABLE ENDERECO(
	ID_ENDERECO NUMBER NOT NULL,
	LOGRADOURO VARCHAR2(255) NOT NULL,
	NUMERO VARCHAR2(8) NOT NULL,
	COMPLEMENTO VARCHAR2 (100),
	CEP VARCHAR2(8) NOT NULL,
	CIDADE VARCHAR2(255) NOT NULL,
	ESTADO VARCHAR2(255) NOT NULL,
	UF VARCHAR2(2) NOT NULL,
	PRIMARY KEY(ID_ENDERECO)
);

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	NOME_CLIENTE VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	CPF VARCHAR2(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	GENERO_CLIENTE VARCHAR2(25) NOT NULL,
	TELEFONE VARCHAR2(11) NOT NULL,
	FOTO_CLIENTE BLOB,
	ID_USUARIO NUMBER NOT NULL,	
	PRIMARY KEY(ID_CLIENTE),
	CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
)

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE USUARIO_CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	ID_ENDERECO NUMBER NOT NULL,
	PRIMARY KEY (ID_CLIENTE, ID_ENDERECO),
	CONSTRAINT FK_CLIENTE_ENDERECO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_CLIENTE_ENDERECO_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE PEDIDO(
	ID_PEDIDO NUMBER NOT NULL,
	FRETE NUMBER NOT NULL,
	PRECO_TOTAL_PRODUTOS NUMBER NOT NULL,
	STATUS VARCHAR2(255),
	ID_CLIENTE NUMBER NOT NULL,
	PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)	 
)

CREATE SEQUENCE SEQ_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE PRODUTO(
	ID_PRODUTO NUMBER NOT NULL,
	NOME_PRODUTO VARCHAR2(255) NOT NULL,
	PRECO NUMBER (8,2) NOT NULL,
	DESCRICAO VARCHAR2(255) NOT NULL,
	IMAGEM BLOB,
	PRIMARY KEY (ID_PRODUTO)
)

CREATE SEQUENCE SEQ_PRODUTO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE ESTOQUE(
	ID_ESTOQUE NUMBER NOT NULL,
	ID_PRODUTO NUMBER NOT NULL,
	TAMANHO VARCHAR2(30) NOT NULL,
	QUANTIDADE NUMBER NOT NULL,
	PRIMARY KEY (ID_ESTOQUE),
	CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
)

CREATE SEQUENCE SEQ_ESTOQUE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE

CREATE TABLE PEDIDO_ESTOQUE(
	ID_PEDIDO NUMBER NOT NULL,
	ID_ESTOQUE NUMBER NOT NULL,
	QUANTIDADE NUMBER NOT NULL,
	TAMANHO VARCHAR2(30) NOT NULL,
	PRECO NUMBER(8,2) NOT NULL,
	PRIMARY KEY (ID_PEDIDO, ID_ESTOQUE),
	CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
	CONSTRAINT FK_ESTOQUE FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE)
)

ALTER TABLE PEDIDO
	ADD ID_PAGAMENTO_STRIPE VARCHAR2(255);


 